endpoints:
  - endpoint:
      request:
        url: "/hello/{name}"
        method: POST
        params:
          - name
          - age
        headers:
          Content-Type: "APPLICATION/JSON"
          Connection: "keep-alive"
        body: >
          '[{
            "type": "cat",
            "age": 23,
            "color": "red"
          }]'
      response:
        headers:
          Content-Type: "APPLICATION/JSON"
          Connection: "keep-alive"
        body: >
          '[{
            "id": 1,
            "type": "cat",
            "age": 23,
            "color": "red",
            "name": "Barsic"
           }]'
        delay: 5s #exception
  - endpoint:
      request:
        url: "/hello/{name}/cat"
        method: GET
        params:
          - age
        headers:
          Content-Type: "APPLICATION/JSON"
          Connection: "keep-alive"
      response:
        headers:
          Content-Type: "APPLICATION/JSON"
          Connection: "keep-alive"
        body: >
          '[{
            "id": 1,
            "type": "cat",
            "age": 23,
            "color": "red",
            "name": "Barsic"
           }]'
        delay: 2s #exception

