endpoints:
  - request:
      uri: "/hello/{}"
      method: POST
    response:
      headers:
        Content-Type: "application/json;charset=utf-8"
        Connection: "keep-alive"
      body: >
        [{
          "id": 1,
          "type": "cat",
          "age": 23,
          "color": "red",
          "name": "Barsic"
         }]
      delay: 2 # (s, ms)
  - request:
      uri: "/hello/{}/cat"
      method: POST
    response:
      headers:
        Content-Type: "application/json;charset=utf-8"
        Connection: "keep-alive"
      body: >
        [{
          "id": 1,
          "type": "cat",
          "age": 23,
          "color": "red",
          "name": "Barsic"
         }]
      delay: 2

