endpoints:
  - request:
      url: "/hello/{name}"
      method: POST
    response:
      headers:
        Content-Type: "APPLICATION/JSON"
        Connection: "keep-alive"
      body: >
        '[{
          "id": 1,
          "type": "cat",
          "age": 23,
          "color": "red",
          "name": "Barsic"
         }]'
      delay: 5 # in seconds
  - request:
      url: "/hello/{name}/cat"
    response:
      headers:
        Content-Type: "APPLICATION/JSON"
        Connection: "keep-alive"
      body: >
        '[{
          "id": 1,
          "type": "cat",
          "age": 23,
          "color": "red",
          "name": "Barsic"
         }]'
      delay: 2s #exception

